# -*- coding: utf-8 -*-
# =============================================================================
# Название процесса: Генератор API документации
# =============================================================================
# Описание:
#   Автоматическое извлечение метаданных маршрутов FastAPI и экспорт в Markdown.
#   Обеспечение актуальности технического описания эндпоинтов.
#
# File: src/api/docs_generator.py
# Project: Ai Assistant (Docker)
# Version: 0.6.0
# Author: hypo69
# =============================================================================

from fastapi import FastAPI
from pathlib import Path

def export_to_markdown(app: FastAPI, output_file: str = "docs/api/autogenerated_reference.md"):
    """Генерация Markdown документации на основе текущих роутов.
    
    ОБОСНОВАНИЕ:
      - Минимизация ручного труда при обновлении API.
      - Предоставление разработчикам актуальных примеров curl.
    """
    lines = ["# API Reference (Autogenerated)\n"]
    lines.append("Данный файл обновляется автоматически при каждом запуске сервера в режиме разработки.\n")
    
    # Перебор всех маршрутов приложения
    # Iteration over all application routes
    for route in app.routes:
        if hasattr(route, "methods"):
            methods = ", ".join(route.methods)
            path = route.path
            summary = getattr(route, "summary", "Заголовок отсутствует")
            
            # Извлечение Docstring (description) из эндпоинта
            # Extraction of the Docstring (description) from the endpoint
            description = getattr(route, "description", "") or route.endpoint.__doc__ or "Описание отсутствует"
            
            lines.append(f"## {summary}")
            if description:
                lines.append(f"{description.strip()}\n")
                
            lines.append(f"**Путь:** `{methods} {path}`\n")
            
            # Формирование примера curl для POST запросов
            # Construction of a curl example for POST requests
            if "POST" in route.methods:
                lines.append("### Пример вызова:\n")
                lines.append("```bash")
                lines.append(f"curl -X POST http://localhost:9696{path} \\")
                lines.append('     -H "Content-Type: application/json" \\')
                lines.append('     -d \'{"param": "value"}\'')
                lines.append("```\n")
            
    # Сохранение результата
    # Saving the result
    output_path = Path(output_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")