# -*- coding: utf-8 -*-
# =============================================================================
# Process Name: MkDocs Nav Generator
# =============================================================================
# Description:
#   Reads mkdocs.template.yml, generates the full nav section from
#   docs/ru/ directory structure and static nav definitions,
#   then writes the complete mkdocs.yml.
#
#   Nav structure:
#     - Static sections (user, admin, dev) defined in NAV_STATIC below
#     - Code Reference section auto-generated by scanning docs/ru/dev/code/
#
# Usage:
#   python scripts/Create-Doc/Generate-Nav.py
#
# File: scripts/Create-Doc/Generate-Nav.py
# Project: AI Assistant (ai_assist)
# Version: 0.8.0
# Author: hypo69
# Copyright: © 2026 hypo69
# License: MIT
# =============================================================================

import os
from pathlib import Path

ROOT     = Path(__file__).resolve().parents[2]
TEMPLATE = ROOT / "mkdocs.template.yml"
OUTPUT   = ROOT / "mkdocs.yml"
DOCS_RU  = ROOT / "docs" / "ru"
CODE_DIR = DOCS_RU / "dev" / "code"

# Directories inside dev/code/ to skip from nav scan
SKIP_CODE_DIRS = {"_nav_fragment.yml"}


def nav_path(md_file: Path) -> str:
    """Absolute path → relative to docs/ru/ for mkdocs nav."""
    return str(md_file.relative_to(DOCS_RU)).replace(os.sep, "/")


def file_title(stem: str) -> str:
    return stem.replace("_", " ").replace("-", " ").title()


def dir_title(name: str) -> str:
    return f"{name}/"


def scan_code_dir(src_dir: Path, indent: int) -> list[str]:
    """Recursively scan docs/ru/dev/code/ and build nav lines."""
    nav: list[str] = []
    pad       = "  " * indent
    inner_pad = "  " * (indent + 1)

    index_md = src_dir / "index.md"
    if not index_md.exists():
        return nav

    nav.append(f"{pad}- {dir_title(src_dir.name)}:")
    nav.append(f"{inner_pad}- Обзор: {nav_path(index_md)}")

    try:
        children = sorted(src_dir.iterdir())
    except PermissionError:
        return nav

    subdirs = [c for c in children
               if c.is_dir() and not c.name.startswith("_")]
    files   = [c for c in children
               if c.is_file() and c.suffix == ".md"
               and c.name != "index.md"
               and not c.name.startswith("_")]

    for sub in subdirs:
        nav.extend(scan_code_dir(sub, indent + 1))

    for f in files:
        nav.append(f"{inner_pad}- {file_title(f.stem)}: {nav_path(f)}")

    return nav


def build_nav() -> str:
    """Build the complete nav YAML string."""

    # Scan dev/code/ for auto-generated code reference
    code_nav_lines: list[str] = []
    if CODE_DIR.exists():
        for d in sorted(CODE_DIR.iterdir()):
            if d.is_dir() and not d.name.startswith("_"):
                code_nav_lines.extend(scan_code_dir(d, indent=0))

    # Indent code nav lines to fit inside "Code Reference:" section (6 spaces)
    code_nav = "\n".join(f"      {line}" for line in code_nav_lines)

    nav = f"""nav:
  - Главная:
    - Обзор: index.md
    - О проекте: about.md
    - Введение: promo/introduction.md

  # ── 👤 Руководство пользователя ──────────────────────────────
  - Руководство пользователя:
    - Начало работы: user/start.md
    - Чат с моделью: user/chat.md
    - Выбор модели: user/choose_model.md
    - База знаний (RAG): user/rag_user.md
    - Продвинутые возможности: user/advanced.md
    - Веб-интерфейс — справка: user/web_interface.md
    - Извлечение текста: user/text_extraction.md
    - Конфигурация (User): user/configuration.md
    - Быстрый старт (User): user/getting_started.md
    - Логирование (User): user/logging.md
    - Telegram боты (User): user/telegram_bots.md
    - Telegram Слушатель (User): user/telegram_listener.md
    - Computer Admin Agent: user/computer_admin_agent.md

  # ── ✨ Промо-материалы / Возможности ──────────────────────────
  - Возможности:
    - Введение в безопасность: promo/introduction.md
    - Безопасность RAG-систем: promo/rag_security.md
    - Корпоративные стандарты: promo/corporate_standards.md
    - Технические требования: promo/technical_requirements.md
    - Безопасность AI-моделей: promo/ai_model_security.md
    - Пятиминутный промо-доклад RU: promo/five_minute_private_ai_pitch.md
    - Пятиминутный промо-доклад HE: promo/five_minute_private_ai_pitch_he.md
    - Фабрика агентов: promo/agent_factory.md
    - Локальный AI vs Облачный: promo/local_vs_cloud.md
    - AI для разработчиков: promo/for_developers.md
    - Бизнес-кейс (ROI): promo/business_roi.md
    - Изоляция и безопасность MCP: promo/mcp_security.md
    - Расширение Kazarinov: promo/kazarinov-extension/index.md

  # ── 🔧 Руководство администратора ────────────────────────────
  - Руководство администратора:
    - Быстрый старт: admin/getting_started.md
    - Установка:
      - Обзор: admin/installation.md
      - install.ps1 — подробно: user/installation.md
    - Конфигурация: admin/configuration.md
    - Параметры генерации: admin/generation_defaults.md
    - Перевод запросов: admin/translation.md
    - Запуск и остановка:
      - Обзор: admin/run_stop.md
      - Локальный workflow: user/local_workflow.md
      - start.ps1: dev/powershell/start.md
      - stop.ps1: dev/powershell/stop.md
      - autostart.ps1: dev/powershell/autostart.md
    - Бэкенды и модели:
      - Обзор: admin/backends.md
      - Работа с моделями: user/models_guide.md
      - llama.cpp — бинарники: user/llama_cpp.md
      - Load-Model.ps1: dev/powershell/Load-Model.md
      - Unload-Model.ps1: dev/powershell/Unload-Model.md
      - List-Models.ps1: dev/powershell/List-Models.md
      - Download-Model.ps1: dev/powershell/Download-Model.md
      - Hf-Models.ps1: dev/powershell/Hf-Models.md
      - Hf-DownloadModel.ps1: dev/powershell/Hf-DownloadModel.md
      - Start-Llama.ps1: dev/powershell/Start-Llama.md
    - RAG — индексы и профили: admin/rag_admin.md
    - Мониторинг и логи: admin/monitoring.md
    - Веб-интерфейс: admin/web_interface.md
    - Telegram боты: admin/telegram_bots.md
    - Telegram Слушатель: admin/telegram_listener.md
    - CLI (cli.ps1): user/cli_reference.md
    - CI/CD документации: user/cicd_docs.md

  # ── 💻 Руководство разработчика ──────────────────────────────
  - Руководство разработчика:
    - Архитектура: dev/architecture.md
    - API Reference: dev/api_reference.md
    - Полный справочник API: dev/api_full.md
    - Карта репозитория: dev/code_reference.md
    - Система RAG:
      - Обзор: dev/rag_system.md
      - Инкрементальный RAG: dev/rag_incremental.md
      - Text Extractor: dev/text_extractor.md
    - OpenCode 1.15.3: dev/opencode_integration.md
    - Агенты:
      - Обзор: dev/agents.md
      - Computer Admin Agent: dev/computer_admin_agent.md
      - MCP Agent: dev/mcp_agent.md
      - Google Agent: dev/google_agent.md
      - Recommender Agent: dev/recommender_agent.md
    - MCP Серверы:
      - Обзор: dev/powershell/index.md
      - McpSTDIOServer.ps1: dev/powershell/mcp-stdio.md
      - McpSystemMonitor.ps1: dev/powershell/McpSystemMonitor.md
      - Подтверждение действий (HITL): dev/mcp_hitl.md
      - Создание кастомного сервера: dev/mcp_custom_server.md
      - McpSTDIOServer.v1.ps1: dev/powershell/McpSTDIOServer.v1.md
      - McpSTDIOServer (ref): dev/powershell/McpSTDIOServer.md
      - McpHttpsServer.ps1: dev/powershell/mcp-https.md
      - McpHttpsServer (ref): dev/powershell/McpHttpsServer.md
      - McpWPCLIServer.ps1: dev/powershell/mcp-wpcli.md
      - McpWPCLIServer (ref): dev/powershell/McpWPCLIServer.md
      - McpWpServer (ref): dev/powershell/McpWpServer.md
      - McpHuggingFaceServer.ps1: dev/powershell/mcp-huggingface-ps.md
      - McpHuggingFaceServer (ref): dev/powershell/McpHuggingFaceServer.md
      - local_models_mcp.py: dev/powershell/mcp-local-models.md
      - ftp_mcp.py: dev/powershell/mcp-ftp.md
      - huggingface_mcp.py: dev/powershell/mcp-huggingface-py.md
      - docs_deploy_mcp.py: dev/powershell/mcp-docs-deploy.md
      - windows_os_mcp.py: dev/powershell/mcp-windows-os.md
      - Start-MCPServers.ps1: dev/powershell/Start-MCPServers.md
      - Invoke-PowerShell.ps1: dev/powershell/Invoke-PowerShell.md
      - Invoke-WpCli.ps1: dev/powershell/Invoke-WpCli.md
    - SDK: dev/sdk.md
    - Дообучение моделей: dev/fine_tuning.md
    - Логирование: dev/logging.md
    - Утилиты (src/utils): dev/utils.md
    - Управление версиями: dev/versioning.md
    - CI/CD документации: dev/cicd_docs.md
    - CI/CD — обзор: cicd/index.md
    - Деплой на FTP: dev/ftp_deploy.md
    - Telegram Боты: dev/telegram_bots.md
    - Telegram Слушатель: dev/telegram_listener.md
    - Скрипты разработки:
      - Обзор: dev/scripts.md
      - Пайплайн документации: dev/doc_pipeline.md
      - Archive-RagIndices.ps1: dev/powershell/Archive-RagIndices.md
      - Clear-ArchivedFiles.ps1: dev/powershell/Clear-ArchivedFiles.md
      - Clear-TempFiles.ps1: dev/powershell/Clear-TempFiles.md
      - Common.ps1: dev/powershell/Common.md
      - Monitor-DiskSpace.ps1: dev/powershell/Monitor-DiskSpace.md
      - Restore-RagIndex.ps1: dev/powershell/Restore-RagIndex.md
      - Rotate-CleanupLog.ps1: dev/powershell/Rotate-CleanupLog.md
      - cli.ps1: dev/powershell/cli.md
      - doc.ps1: dev/powershell/doc.md
      - Build-Exes.ps1: dev/powershell/Build-Exes.md
      - Create-Requirements.ps1: dev/powershell/Create-Requirements.md
      - Generate-PsDocs.ps1: dev/powershell/Generate-PsDocs.md
      - Get-FoundryUtils.ps1: dev/powershell/Get-FoundryUtils.md
      - Get-TelegramChatId.ps1: dev/powershell/Get-TelegramChatId.md
      - Get-ServiceStatus.ps1: dev/powershell/Get-ServiceStatus.md
      - Check-Port.ps1: dev/powershell/Check-Port.md
      - Restart-MkDocs.ps1: dev/powershell/Restart-MkDocs.md
      - Update-Project.ps1: dev/powershell/Update-Project.md
      - Fix-Vulnerabilities.ps1: dev/powershell/Fix-Vulnerabilities.md
      - Setup-GitHooks.ps1: dev/powershell/Setup-GitHooks.md
      - Install-Ollama.ps1: dev/powershell/Install-Ollama.md
      - Install-OpenCode.ps1: dev/powershell/Install-OpenCode.md
      - Install-Winget.ps1: dev/powershell/Install-Winget.md
      - Invoke-APIRequest.ps1: dev/powershell/Invoke-APIRequest.md
      - Invoke-FastApiRequest.ps1: dev/powershell/Invoke-FastApiRequest.md
      - Invoke-LoggedCommand.ps1: dev/powershell/Invoke-LoggedCommand.md
      - Invoke-OsDiagnostic.ps1: dev/powershell/Invoke-OsDiagnostic.md
      - Build-Release.ps1: dev/powershell/Build-Release.md
      - Invoke-EnvMigration.ps1: dev/powershell/Invoke-EnvMigration.md
      - New-Release.ps1: dev/powershell/New-Release.md
      - run-qa.ps1: dev/powershell/run-qa.md
      - Step-Backends.ps1: dev/powershell/Step-Backends.md
      - Step-ConfigAndData.ps1: dev/powershell/Step-ConfigAndData.md
      - Step-Finalize.ps1: dev/powershell/Step-Finalize.md
      - Step-PythonEnvironment.ps1: dev/powershell/Step-PythonEnvironment.md
      - Step-UserInterface.ps1: dev/powershell/Step-UserInterface.md
    - Code Reference:
      - Обзор: dev/code/index.md
{code_nav}

  # ── Браузерные расширения ─────────────────────────────────────
  - Браузерные расширения:
    - JavaScript Overview: dev/js/index.md
    - Summarizer:
      - Обзор: dev/extensions/browser-extension-summarizer/index.md
      - Архитектура: dev/extensions/browser-extension-summarizer/architecture.md
      - Установка: dev/extensions/browser-extension-summarizer/installation.md
      - Провайдеры: dev/extensions/browser-extension-summarizer/providers.md
      - Суммаризация: dev/extensions/browser-extension-summarizer/summarization.md
      - Чат: dev/extensions/browser-extension-summarizer/chat.md
      - Отладка: dev/extensions/browser-extension-summarizer/debug.md
      - Многоязычность: dev/extensions/browser-extension-summarizer/i18n.md
      - Стили и UI: dev/extensions/browser-extension-summarizer/styles.md
      - Хранилище: dev/extensions/browser-extension-summarizer/storage.md
      - API Reference: dev/extensions/browser-extension-summarizer/api_reference.md

  # ── 🛡️ QA / Тестирование ─────────────────────────────────────
  - QA / Тестирование:
    - Обзор: qa/index.md
    - Стратегия: qa/strategy.md
    - Запуск тестов: qa/running.md
    - Юнит-тесты: qa/unit.md
    - Интеграционные тесты: qa/integration.md
    - Тесты агентов: qa/agents.md
    - QA скрипты:
      - Invoke-Qa.ps1: dev/powershell/Invoke-Qa.md
      - Invoke-QaInstall.ps1: dev/powershell/Invoke-QaInstall.md
      - Invoke-QaStart.ps1: dev/powershell/Invoke-QaStart.md
      - Watch-Tests.ps1: dev/powershell/Watch-Tests.md
      - run-load-tests.ps1: dev/powershell/run-load-tests.md
      - LlamaExtraction.Tests.ps1: dev/powershell/LlamaExtraction.Tests.md
      - InstallLMStudio.Tests.ps1: dev/powershell/InstallLMStudio.Tests.md
      - start.Tests.ps1: dev/powershell/start.Tests.md
      - Monitor-DiskSpace.Tests.ps1: dev/powershell/Monitor-DiskSpace.Tests.md
      - Restore-RagIndex.Tests.ps1: dev/powershell/Restore-RagIndex.Tests.md
      - Start-Project.Tests.ps1: dev/powershell/Start-Project.Tests.md
      - Clear-Reports.ps1: dev/powershell/Clear-Reports.md
      - Test-ApiEndpoints.ps1: dev/powershell/Test-ApiEndpoints.md
      - test_api_endpoints.ps1: dev/powershell/test_api_endpoints.md

  # ── Прочее ────────────────────────────────────────────────────
  - Прочее:
    - install.md: install.md
    - qa.md: qa.md

  - 🌐 Онлайн документация: https://davidka.net/ai_assist/docs
"""
    return nav


def main() -> None:
    if not TEMPLATE.exists():
        print(f"ERROR: {TEMPLATE} not found")
        return

    template = TEMPLATE.read_text(encoding="utf-8")
    nav      = build_nav()

    result = template.rstrip() + "\n\n" + nav
    OUTPUT.write_text(result, encoding="utf-8")
    print(f"✅ mkdocs.yml generated ({OUTPUT})")


if __name__ == "__main__":
    main()
